# synology-dsm service entries description.

update:
  name: Music Update
  description: Update when the current music state changes.
  fields:
    entity_id:
      name: Entity ID
      description: The entity that has updated
      required: true
      advanced: false
      example: media_player.spotify
      selector:
        text:
          multiline: false
    friendly_entity:
      name: Friendly Entity Name
      description: A Friendly version of the entity name
      required: false
      advanced: false
      example: Spotify
      selector:
        text:
          multiline: false
    old_state:
      name: Old State
      description: The old state.
      required: false
      advanced: true
      example: playing
      selector:
        text:
          multiline: false
    old_title:
      name: Old State - Media Title
      description: The old state of the Media Title.
      required: false
      advanced: true
      example: The Unicorn Invasion of Dundee
      selector:
        text:
          multiline: false
    old_artist:
      name: Old State - Media Artist
      description: The old state of the Media Artist.
      required: false
      advanced: true
      example: Gloryhammer
      selector:
        text:
          multiline: false
    old_album:
      name: Old State - Media Album
      description: The old state of the Media Album.
      required: false
      advanced: true
      example: Tales from the Kingdom of Fife
      selector:
        text:
          multiline: false
    new_state:
      name: New State
      description: The new state.
      required: true
      advanced: false
      example: playing
      selector:
        text:
          multiline: false
    new_title:
      name: New State - Media Title
      description: The New state of the Media Title.
      required: true
      advanced: false
      example: Rex Regi Rebellis
      selector:
        text:
          multiline: false
    new_artist:
      name: New State - Media Artist
      description: The New state of the Media Artist.
      required: true
      advanced: false
      example: Turisas
      selector:
        text:
          multiline: false
    new_album:
      name: New State - Media Album
      description: The New state of the Media Album.
      required: true
      advanced: false
      example: Battle Metal
      selector:
        text:
          multiline: false

alarm:
  name: Trigger Alarm
  description: Create and play a new playlist as an alarm clock.
  fields:

speak:
  name: Speak a Message
  description: Speak a Message
  fields:
    message:
      name: Message
      description: The Message to Read
      required: true
      advanced: false
      example: Hello, Here is a message
      selector:
        text:
          multiline: false
    bell:
      name: Bell
      description: The Bell to Play
      required: true
      advanced: false
      example: Default
      selector:
        select:
          options:
            - "OneUp"
            - "Achievement"
            - "Announcement"
            - "BellAnnouncement" 
            - "Default"
            - "ElectronicBeep"
            - "ErrorBeep"
            - "FairyBells"
            - "PoliceHorn"
            - "Positive"
            - "SoftDing"
            - "None"

bell:
  name: Bell Alert
  description: Ring an announcement bell
  fields:
    bell:
      name: Bell
      description: The Bell to Play
      required: true
      advanced: false
      example: Default
      selector:
        select:
          options:
            - "OneUp"
            - "Achievement"
            - "Announcement"
            - "BellAnnouncement" 
            - "Default"
            - "ElectronicBeep"
            - "ErrorBeep"
            - "FairyBells"
            - "PoliceHorn"
            - "Positive"
            - "SoftDing"
            - "None"

tempmsg:
  name: Display a temporary message
  description: Display a temporary message.
  fields:
    line_1:
      name: Line 1
      description: The First Line of the Message to Display
      required: true
      advanced: false
      example: Hello, Here is a message
      selector:
        text:
          multiline: false
    line_2:
      name: Line 2
      description: The Second Line of the Message to Display
      required: true
      advanced: false
      example: Hello, Here is a message
      selector:
        text:
          multiline: false